=== tchikichev/dtcd_gen_primitives/es_primitives/src/parse/node.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "primitiveID": {
            "type": "string"
        },
        "primitiveName": {
            "type": "string"
        },
        "properties": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                },
                "aliasName": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                },
                "description": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                },
                "normallylnService": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                },
                "type": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                },
                "accuracyClass": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "expression",
                        "type",
                        "status",
                        "value"
                    ]
                }
            },
            "required": [
                "name",
                "aliasName",
                "description",
                "normallylnService",
                "type",
                "accuracyClass"
            ]
        },
        "nodeTitle": {
            "type": "string"
        },
        "image": {
            "type": "string"
        },
        "initPorts": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "properties": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        },
                                        "expression": {
                                            "type": "string"
                                        },
                                        "status": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "expression",
                                        "status",
                                        "value"
                                    ]
                                }
                            },
                            "required": [
                                "status"
                            ]
                        },
                        "primitiveName": {
                            "type": "string"
                        },
                        "initPosition": {
                            "type": "object",
                            "properties": {
                                "x": {
                                    "type": "number"
                                },
                                "y": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        },
                        "primitiveID": {
                            "type": "string"
                        },
                        "location": {
                            "type": "object",
                            "properties": {
                                "x": {
                                    "type": "number"
                                },
                                "y": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        }
                    },
                    "required": [
                        "type",
                        "properties",
                        "primitiveName",
                        "initPosition",
                        "primitiveID",
                        "location"
                    ]
                },
                {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "properties": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        },
                                        "expression": {
                                            "type": "string"
                                        },
                                        "status": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "expression",
                                        "status",
                                        "value"
                                    ]
                                }
                            },
                            "required": [
                                "status"
                            ]
                        },
                        "primitiveName": {
                            "type": "string"
                        },
                        "initPosition": {
                            "type": "object",
                            "properties": {
                                "x": {
                                    "type": "number"
                                },
                                "y": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        },
                        "primitiveID": {
                            "type": "string"
                        },
                        "location": {
                            "type": "object",
                            "properties": {
                                "x": {
                                    "type": "number"
                                },
                                "y": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        }
                    },
                    "required": [
                        "type",
                        "properties",
                        "primitiveName",
                        "initPosition",
                        "primitiveID",
                        "location"
                    ]
                }
            ]
        },
        "layout": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "number"
                },
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            },
            "required": [
                "x",
                "y",
                "height",
                "width"
            ]
        }
    },
    "required": [
        "primitiveID",
        "primitiveName",
        "properties",
        "nodeTitle",
        "image",
        "initPorts",
        "layout"
    ]
}

=== tchikichev/dtcd_gen_primitives/es_primitives/src/parse/ex_node.json
{
  "primitiveID": "esTopTransformer_2",
  "primitiveName": "esTopTransformer",
  "properties": {
      "name": {
      "expression": "//\"Наименование объекта информационной модели\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    },
    "aliasName": {
      "expression": "//\"Дополнительное наименование идентифицируемого объекта\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    },
    "description": {
      "expression": "//\"Описание объекта информационной модели\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    },
    "normallylnService": {
      "expression": "//\"Нормальное состояние оборудования - в работе (если присвоено значение Истина)\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    },
    "type": {
      "expression": "//\"Конструктивный тип\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    },
    "accuracyClass": {
      "expression": "//\"Класс точности\"\n' '",
      "type": "expression",
      "status": "complete",
      "value": ""
    }
  },
  "nodeTitle": "$this.primitiveID$",
  "image": "/rawPrimitives/esTopTransformer/icon.svg",
  "initPorts": [
    {
      "type": [
        "IN",
        "OUT"
      ],
      "properties": {
        "status": {
          "type": "expression",
          "expression": "",
          "status": "complete",
          "value": ""
        }
      },
      "primitiveName": "ioPortLow1",
      "initPosition": {
        "x": 0.5,
        "y": 1
      },
      "primitiveID": "esTopTransformer_2_ioPortLow1",
      "location": {
        "x": -3707.5,
        "y": -1574.75
      }
    },
    {
      "type": [
        "IN",
        "OUT"
      ],
      "properties": {
        "status": {
          "type": "expression",
          "expression": "",
          "status": "complete",
          "value": ""
        }
      },
      "primitiveName": "ioPortTop2",
      "initPosition": {
        "x": 0.5,
        "y": 0
      },
      "primitiveID": "esTopTransformer_2_ioPortTop2",
      "location": {
        "x": -3707.5,
        "y": -1665.75
      }
    }
  ],
  "layout": {
    "x": -3753,
    "y": -1665.75,
    "height": 91,
    "width": 91
  }
}
